In [5]:
import numpy as np

## DataTypes & Attributes

In [7]:
# NumPy's main datatype is ndarray
# 1 dimensonal array
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [8]:
#check the type
type(a1)

numpy.ndarray

In [14]:
#2 dimensional array
a2 = np.array([[1,2.0,3.3],[4,5,6.5]])
a3 = np.array([
    [
        [1,2,3],[4,5,6],[7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]
])

In [15]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [16]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
# attributes of array

In [17]:
a1.shape

(3,)

In [18]:
a2.shape

(2, 3)

In [19]:
a3.shape

(2, 3, 3)

In [20]:
# number of dimensions
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [21]:
# data type of array
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [22]:
# size of array
a1.size,a2.size,a3.size

(3, 6, 18)

In [23]:
# type
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [25]:
# Create a Dataframe from a NumPy array
import pandas as pd
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5