In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
# 1 dimensonal array
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [8]:
#check the type
type(a1)

numpy.ndarray

In [3]:
#2 dimensional array
a2 = np.array([[1,2.0,3.3],[4,5,6.5]])
a3 = np.array([
    [
        [1,2,3],[4,5,6],[7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]
])

In [4]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
# attributes of array

In [17]:
a1.shape

(3,)

In [18]:
a2.shape

(2, 3)

In [19]:
a3.shape

(2, 3, 3)

In [20]:
# number of dimensions
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [21]:
# data type of array
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [22]:
# size of array
a1.size,a2.size,a3.size

(3, 6, 18)

In [23]:
# type
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [25]:
# Create a Dataframe from a NumPy array
import pandas as pd
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2.Creating arrays

In [26]:
# create a sample array filled with ones
# enter shift+tab over the function to see the functions
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
#types
ones.dtype

dtype('float64')

In [28]:
# intialize an array with zeroes
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
#range array - start(0), stop(10) , step 2
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [18]:
# method -1 fill array with random values
# low - 0, high,10, size=(3,5) size of numpy array 
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[3, 5, 8, 8, 7],
       [5, 0, 0, 2, 8],
       [9, 6, 4, 9, 7]])

In [35]:
random_array.size

15

In [36]:
random_array.shape

(3, 5)

In [37]:
# method -2 fill array with random values .random
random_array_2=np.random.random((5,3))
random_array_2

array([[0.73285788, 0.10965358, 0.54555105],
       [0.46567665, 0.75729722, 0.89821131],
       [0.22804504, 0.56651075, 0.71092391],
       [0.87806937, 0.657448  , 0.6329956 ],
       [0.96067997, 0.32363812, 0.97594201]])

In [41]:
# method -3 fill array with random values - .rand
random_array_3=np.random.rand(5,3)
random_array_3

array([[0.53824449, 0.49968844, 0.40578042],
       [0.05142316, 0.05563771, 0.06350082],
       [0.04492   , 0.27349652, 0.33535499],
       [0.96758908, 0.12721486, 0.33977019],
       [0.56175465, 0.02876552, 0.98058978]])

In [16]:
# Pseudo-random numbsers
# we can specify a np.random.seed(1)or np.random.seed(n) - which will generate a random set of numbers 
# but this random set of numbers can be replicated every time we specify the n value inside np.random.seed(n)
np.random.seed(7)
random_array_4=np.random.random((5,3))
random_array_4

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing arrrays and matrices

In [19]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[3, 3, 8, 3, 0],
       [1, 0, 0, 6, 7],
       [7, 9, 3, 0, 7]])

In [20]:
# find the unique elements in an array
np.unique(random_array)

array([0, 1, 3, 6, 7, 8, 9])

In [21]:
a1=np.array([1,2,3])
a2 = np.array([[1,2.0,3.3],[4,5,6.5]])
a3 = np.array([
    [
        [1,2,3],[4,5,6],[7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]
])

In [22]:
a1,a2,a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [23]:
a1[1]

2

In [24]:
a2[1]

array([4. , 5. , 6.5])

In [27]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [28]:
#display first two columns of row column and array
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [29]:
# create a 4 dimensional array
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3],
         [4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2]],

        [[2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5],
         [3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8]],

        [[6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4],
         [9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1]]],


       [[[6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9],
         [7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8]],

        [[3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2],
         [0, 5, 3, 0, 5],
         [7, 1, 8, 4, 9]],

        [[0, 2, 0, 7, 6],
         [2, 9, 9, 5, 1],
         [0, 0, 9, 1, 1],
         [5, 3, 2, 0, 4]]]])

In [30]:
#display shape and dimensions
a4.shape,a4.ndim

((2, 3, 4, 5), 4)

In [ ]:
#get the first 4 numbers of inner most arrays

In [ ]:
#slice the first 3 dimensions and slice the final dimension(containing 5) one with only 4 remaining

In [31]:
a4[:,:,:,:4]

array([[[[7, 7, 0, 5],
         [3, 1, 3, 1],
         [4, 3, 1, 9],
         [9, 1, 2, 3]],

        [[2, 5, 7, 3],
         [9, 9, 3, 4],
         [3, 0, 4, 8],
         [7, 2, 7, 3]],

        [[6, 6, 5, 6],
         [7, 1, 5, 4],
         [9, 9, 0, 6],
         [6, 8, 2, 4]]],


       [[[6, 1, 5, 1],
         [9, 8, 6, 5],
         [7, 5, 4, 9],
         [8, 1, 5, 5]],

        [[3, 7, 7, 9],
         [7, 5, 9, 6],
         [0, 5, 3, 0],
         [7, 1, 8, 4]],

        [[0, 2, 0, 7],
         [2, 9, 9, 5],
         [0, 0, 9, 1],
         [5, 3, 2, 0]]]])

In [32]:
#more examples
a4[:,:,:,:3]

array([[[[7, 7, 0],
         [3, 1, 3],
         [4, 3, 1],
         [9, 1, 2]],

        [[2, 5, 7],
         [9, 9, 3],
         [3, 0, 4],
         [7, 2, 7]],

        [[6, 6, 5],
         [7, 1, 5],
         [9, 9, 0],
         [6, 8, 2]]],


       [[[6, 1, 5],
         [9, 8, 6],
         [7, 5, 4],
         [8, 1, 5]],

        [[3, 7, 7],
         [7, 5, 9],
         [0, 5, 3],
         [7, 1, 8]],

        [[0, 2, 0],
         [2, 9, 9],
         [0, 0, 9],
         [5, 3, 2]]]])

In [33]:
a4[:,:,:,:2]

array([[[[7, 7],
         [3, 1],
         [4, 3],
         [9, 1]],

        [[2, 5],
         [9, 9],
         [3, 0],
         [7, 2]],

        [[6, 6],
         [7, 1],
         [9, 9],
         [6, 8]]],


       [[[6, 1],
         [9, 8],
         [7, 5],
         [8, 1]],

        [[3, 7],
         [7, 5],
         [0, 5],
         [7, 1]],

        [[0, 2],
         [2, 9],
         [0, 0],
         [5, 3]]]])

In [34]:
a4[:,:,:,:1]

array([[[[7],
         [3],
         [4],
         [9]],

        [[2],
         [9],
         [3],
         [7]],

        [[6],
         [7],
         [9],
         [6]]],


       [[[6],
         [9],
         [7],
         [8]],

        [[3],
         [7],
         [0],
         [7]],

        [[0],
         [2],
         [0],
         [5]]]])

# 4. Manipulating & comparng arrays

## Arithmetic

In [7]:
a1

array([1, 2, 3])

In [9]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [10]:
a1+ones # same as np.add(a1,ones)

array([2., 3., 4.])

In [11]:
a1-ones

array([0., 1., 2.])

In [12]:
a1*ones

array([1., 2., 3.])

In [14]:
a1


array([1, 2, 3])

In [15]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [13]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [16]:
# this below code will cause broadcasting error
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
# How can you reshape a2 to be compatible with a3?
# Search : "How to reshape numpy array"

In [17]:
a1/ones

array([1., 2., 3.])

In [18]:
a2/a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [19]:
# // - floor division removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [21]:
# ** - squares the numbers
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [22]:
# shows modulo - the remainder
a1 % 2

array([1, 0, 1], dtype=int32)

In [25]:
# shows exponential
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [26]:
# show log
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation

Aggregation = performing the same operation on a number of things

sum is available for both python list as well as numpy arrays, Use Python's methods (sum()) on Python datatypes and use NumPy's methods on Mumpy arrays (np.sum())

In [27]:
# create a massive numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [28]:
massive_array[:10]

array([0.26830027, 0.83464351, 0.87156299, 0.48655868, 0.84278665,
       0.96109087, 0.36739181, 0.09987492, 0.82011258, 0.72765455])

In [ ]:
# %timeit - specifies how long a particular code takes to run

In [29]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # Numpy's np.sum()

9.19 ms ± 262 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
37.6 µs ± 645 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [30]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [31]:
np.mean(a2)

3.6333333333333333

In [32]:
np.max(a2)

6.5

In [33]:
# standard deviation - a measure of how spread out a group of numbers is from the mean
# sd is square root of variance
# if no axis is passed sd is applied to whole array
np.std(a2)

1.8226964152656422

In [35]:
# variance - measure of the average degree to which each number is different to the mean
# higher variance = wider range of numbers
# lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [36]:
# sd = square root of variance
np.sqrt(np.var(a2))

1.8226964152656422